# 指定平台和最低版本
platform :ios, '14.0'

# 抑制所有 Pod 的警告
inhibit_all_warnings!

target 'SmartSelfieApp' do
  # 使用框架而非静态库
  use_frameworks!

  # 添加所需的 Pod
  pod 'Alamofire', '~> 5.4'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'SnapKit', '~> 5.0'
  pod 'RealmSwift', '~> 10.7'
  pod 'Kingfisher', '~> 7.0'
  pod 'RxSwift', '~> 6.0'
  pod 'RxCocoa', '~> 6.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRealm', '~> 5.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxSwiftExt', '~> 5.0'
  pod 'RxOptional', '~> 5.0'
  pod 'RxAlamofire', '~> 6.0'
  pod 'RxKingfisher', '~> 1.0'
  pod 'RxSwiftUtilities', '~> 0.6'
  pod 'RxViewController', '~> 1.0'
  pod 'RxKeyboard', '~> 2.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRealmDataSources', '~> 0.1'
  pod 'RxRealmExtensions', '~> 0.1'
  pod 'RxRealm', '~> 5.0'
  pod 'RxOptional', '~> 5.0'
  pod 'RxSwiftExt', '~> 5.0'
  pod 'RxSwiftUtilities', '~> 0.6'
  pod 'RxViewController', '~> 1.0'
  pod 'RxKeyboard', '~> 2.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRealmDataSources', '~> 0.1'
  pod 'RxRealmExtensions', '~> 0.1'
  pod 'RxRealm', '~> 5.0'
  pod 'RxOptional', '~> 5.0'
  pod 'RxSwiftExt', '~> 5.0'
  pod 'RxSwiftUtilities', '~> 0.6'
  pod 'RxViewController', '~> 1.0'
  pod 'RxKeyboard', '~> 2.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRealmDataSources', '~> 0.1'
  pod 'RxRealmExtensions', '~> 0.1'
  pod 'RxRealm', '~> 5.0'
  pod 'RxOptional', '~> 5.0'
  pod 'RxSwiftExt', '~> 5.0'
  pod 'RxSwiftUtilities', '~> 0.6'
  pod 'RxViewController', '~> 1.0'
  pod 'RxKeyboard', '~> 2.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRealmDataSources', '~> 0.1'
  pod 'RxRealmExtensions', '~> 0.1'
  pod 'RxRealm', '~> 5.0'
  pod 'RxOptional', '~> 5.0'
  pod 'RxSwiftExt', '~> 5.0'
  pod 'RxSwiftUtilities', '~> 0.6'
  pod 'RxViewController', '~> 1.0'
  pod 'RxKeyboard', '~> 2.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRealmDataSources', '~> 0.1'
  pod 'RxRealmExtensions', '~> 0.1'
  pod 'RxRealm', '~> 5.0'
  pod 'RxOptional', '~> 5.0'
  pod 'RxSwiftExt', '~> 5.0'
  pod 'RxSwiftUtilities', '~> 0.6'
  pod 'RxViewController', '~> 1.0'
  pod 'RxKeyboard', '~> 2.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRealmDataSources', '~> 0.1'
  pod 'RxRealmExtensions', '~> 0.1'
  pod 'RxRealm', '~> 5.0'
  pod 'RxOptional', '~> 5.0'
  pod 'RxSwiftExt', '~> 5.0'
  pod 'RxSwiftUtilities', '~> 0.6'
  pod 'RxViewController', '~> 1.0'
  pod 'RxKeyboard', '~> 2.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRealmDataSources', '~> 0.1'
  pod 'RxRealmExtensions', '~> 0.1'
  pod 'RxRealm', '~> 5.0'
  pod 'RxOptional', '~> 5.0'
  pod 'RxSwiftExt', '~> 5.0'
  pod 'RxSwiftUtilities', '~> 0.6'
  pod 'RxViewController', '~> 1.0'
  pod 'RxKeyboard', '~> 2.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRealmDataSources', '~> 0.1'
  pod 'RxRealmExtensions', '~> 0.1'
  pod 'RxRealm', '~> 5.0'
  pod 'RxOptional', '~> 5.0'
  pod 'RxSwiftExt', '~> 5.0'
  pod 'RxSwiftUtilities', '~> 0.6'
  pod 'RxViewController', '~> 1.0'
  pod 'RxKeyboard', '~> 2.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRealmDataSources', '~> 0.1'
  pod 'RxRealmExtensions', '~> 0.1'
  pod 'RxRealm', '~> 5.0'
  pod 'RxOptional', '~> 5.0'
  pod 'RxSwiftExt', '~> 5.0'
  pod 'RxSwift 