name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        run: pod install

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'  # 根据项目要求设置 Xcode 版本

      - name: Build SmartSelfieApp
        run: |
          xcodebuild -workspace SmartSelfieApp.xcworkspace \
                     -scheme SmartSelfieApp \
                     -sdk iphoneos \
                     -configuration Release \
                     clean build